// lib/shortlistsData.js
// Centralised shortlist metadata so multiple pages (Shortlists, Search, Related blocks)
// can share the same source of truth.

// NOTE: Keep labels consistent with URL slugs, and keep the list intentionally short.
// Tags power filtering and "related shortlists" suggestions.

export const SHORTLIST_SECTIONS = [
  {
    title: 'Home essentials',
    desc: 'Air, water, humidity and the highest‑impact home swaps.',
    items: [
      {
        label: 'Air purifiers for allergies (UK)',
        href: '/best-air-purifiers-allergies-uk',
        tag: 'Air',
        desc: 'Shortlist for common UK rooms with clear size guidance and trade‑offs.',
        bestFor: 'Allergies + general air comfort',
        tradeOff: 'Filter costs matter long‑term',
        updated: '2026-02-08',
      },
      {
        label: 'Air purifiers for small flats (UK)',
        href: '/best-air-purifiers-small-flats-uk',
        tag: 'Air',
        desc: 'Compact options that make sense in smaller rooms.',
        bestFor: 'Bedrooms + small living spaces',
        tradeOff: 'Noise vs performance',
        updated: '2026-02-08',
      },
      {
        label: 'Dehumidifiers for damp & mould (UK)',
        href: '/best-dehumidifiers-damp-mould-uk',
        tag: 'Humidity',
        desc: 'Shortlist with the key spec checks and real‑world trade‑offs.',
        bestFor: 'Damp, condensation, mould risk',
        tradeOff: 'Noise + power use',
        updated: '2026-02-08',
      },
      {
        label: 'Water filters (UK)',
        href: '/best-water-filters-uk',
        tag: 'Water',
        desc: 'Jugs vs under‑sink vs countertop: keep it simple, check running costs.',
        bestFor: 'Taste + convenience',
        tradeOff: 'Replacement filters',
        updated: '2026-02-02',
      },
      {
        label: 'Shower filters (UK hard water)',
        href: '/best-shower-filters-uk-hard-water',
        tag: 'Shower',
        desc: 'Comfort‑first shortlist for hard‑water homes.',
        bestFor: 'Dry skin + hair feel',
        tradeOff: 'Cartridges need replacing',
        updated: '2026-02-08',
      },
      {
        label: 'Fragrance‑free laundry detergents (UK)',
        href: '/best-fragrance-free-laundry-detergents-uk',
        tag: 'Laundry',
        desc: 'Sensitive‑home options with ingredients to avoid.',
        bestFor: 'Sensitive skin + bedding',
        tradeOff: 'Availability varies',
        updated: '2026-02-08',
      },
      {
        label: 'Meaco Arete One 20L (UK)',
        href: '/best-dehumidifier-air-purifier-uk-meaco-arete-one-20l',
        tag: 'Humidity',
        desc: 'A featured UK option for damp + laundry drying, with a practical size checklist.',
        bestFor: 'Humidity control + laundry',
        tradeOff: 'Noise + running cost',
        updated: '2026-02-13',
      },
      {
        label: 'Meaco Arete One 25L (UK)',
        href: '/best-dehumidifier-air-purifier-uk-meaco-arete-one-25l',
        tag: 'Humidity',
        desc: 'A higher-capacity Meaco option if you’re tackling larger spaces or heavier moisture loads.',
        bestFor: 'Bigger homes + heavier damp',
        tradeOff: 'Noise + running cost',
        updated: '2026-02-13',
      },
      {
        label: 'Reverse osmosis system (UK): Waterdrop G3P600',
        href: '/best-reverse-osmosis-water-filter-uk-waterdrop-g3p600',
        tag: 'Water',
        desc: 'Fast-flow under-sink RO option: what to check before you buy and install.',
        bestFor: 'High-volume filtered water',
        tradeOff: 'Install + filter changes',
        updated: '2026-02-13',
      },
      {
        label: 'Countertop water filter (UK): Doulton Biotect Ultra',
        href: '/best-countertop-water-filter-uk-doulton-biotect-ultra',
        tag: 'Water',
        desc: 'Renter-friendly countertop option: pros/cons, cartridges, and what to avoid.',
        bestFor: 'No-plumbing kitchens',
        tradeOff: 'Counter space + cartridge cost',
        updated: '2026-02-13',
      },
      {
        label: 'Bathroom swap: natural loofah sponge (UK)',
        href: '/best-natural-loofah-sponge-uk-jungleculture',
        tag: 'Low-tox',
        desc: 'A plastic-free shower swap: how to use, dry, and replace it safely.',
        bestFor: 'Simple low-tox basics',
        tradeOff: 'Needs drying + replacing',
        updated: '2026-02-13',
      },
      {
        label: 'Hand cream (UK): Atenai Oasis',
        href: '/best-hand-cream-uk-atenai-oasis-hand-cream',
        tag: 'Low-tox',
        desc: 'A simple daily hand-cream option: what to check if you’re fragrance-sensitive.',
        bestFor: 'Dry hands + simple routines',
        tradeOff: 'Patch test if sensitive',
        updated: '2026-02-13',
      },

    ],
  },
  {
    title: 'Sleep',
    desc: 'Simple, conservative options to support a better routine.',
    items: [
      {
        label: 'Natural sleep support',
        href: '/best-natural-sleep-support',
        tag: 'Sleep',
        desc: 'A short, sensible shortlist for wind‑down support (UK).',
        bestFor: 'Winding down',
        tradeOff: 'Responses vary',
        updated: '2026-02-08',
      },
      {
        label: 'Natural sleep remedies (non‑pharma)',
        href: '/best-natural-sleep-remedies-non-pharma',
        tag: 'Sleep',
        desc: 'Non‑pharma support options with clear expectations.',
        bestFor: 'Low‑risk options',
        tradeOff: 'Not magic fixes',
        updated: '2026-02-08',
      },
      {
        label: 'Humidifiers for bedrooms (UK)',
        href: '/best-humidifiers-for-bedrooms-uk',
        tag: 'Humidity',
        desc: 'Shortlist for dry rooms + sleep comfort.',
        bestFor: 'Dry air, night comfort',
        tradeOff: 'Cleaning is non‑negotiable',
        updated: '2026-02-08',
      },
{
        label: 'Magnesium for wind‑down (UK)',
        href: '/best-marine-magnesium-supplement-uk-together-sleep',
        tag: 'Sleep',
        desc: 'A conservative magnesium guide: how to start, what forms to look for, and who should be cautious.',
        bestFor: 'Routine support',
        tradeOff: 'Responses vary',
        updated: '2026-02-11',
      },
      {
        label: 'Mattress upgrade (UK)',
        href: '/best-mattress-for-sleep-uk-simba-hybrid-original',
        tag: 'Sleep',
        desc: 'A simple mattress guide focused on comfort, support, temperature, and using trials well.',
        bestFor: 'Comfort + support',
        tradeOff: 'Price + trial logistics',
        updated: '2026-02-11',
      },

      {
        label: 'Duvet for hot sleepers (UK): Simba Hybrid® Duvet',
        href: '/best-duvet-for-hot-sleepers-uk-simba-hybrid-duvet',
        tag: 'Sleep',
        desc: 'A temperature-focused duvet guide with what to check (fills, returns, care).',
        bestFor: 'Hot sleepers',
        tradeOff: 'Trial/returns matter',
        updated: '2026-02-13',
      },
      {
        label: 'Magnesium complex (UK): Simply Supplements',
        href: '/best-magnesium-complex-uk-simplysupplements-magnesium-complex',
        tag: 'Sleep',
        desc: 'A practical magnesium guide: what forms matter, how to start, and common mistakes.',
        bestFor: 'Wind-down routines',
        tradeOff: 'Tolerance varies',
        updated: '2026-02-13',
      },
      {
        label: 'Calm support (UK): Saffrosun® Calm',
        href: '/best-saffron-supplement-uk-naked-pharmacy-saffrosun-calm',
        tag: 'Sleep',
        desc: 'A simple, cautious guide to saffron-style calm support and what to check.',
        bestFor: 'Evening routines',
        tradeOff: 'Responses vary',
        updated: '2026-02-13',
      },

    ],
  },
  {
    title: 'Nutrition staples (UK)',
    desc: 'Simple single‑ingredient staples that compound over time.',
    items: [
      {
        label: 'Extra virgin olive oil (UK)',
        href: '/best-extra-virgin-olive-oil-uk',
        tag: 'Staples',
        desc: 'A shortlist focused on freshness and sensible buying.',
        bestFor: 'Daily cooking + salads',
        tradeOff: 'Freshness matters',
        updated: '2026-02-08',
      },
      {
        label: 'Organic oats (UK)',
        href: '/best-organic-oats-uk',
        tag: 'Staples',
        desc: 'Jumbo/rolled/steel‑cut: simple options, no overwhelm.',
        bestFor: 'Daily breakfast',
        tradeOff: 'Buy what you’ll finish',
        updated: '2026-02-08',
      },
      {
        label: 'Chia seeds (UK)',
        href: '/best-chia-seeds-uk',
        tag: 'Superfoods',
        desc: 'Simple add‑ins for oats, yoghurt, smoothies.',
        bestFor: 'Fibre + easy meals',
        tradeOff: 'Hydration matters',
        updated: '2026-02-08',
      },
      {
        label: 'Flaxseed (UK)',
        href: '/best-ground-flaxseed-uk',
        tag: 'Superfoods',
        desc: 'Ground vs whole: easy, practical shortlist.',
        bestFor: 'Fibre + healthy fats',
        tradeOff: 'Freshness + storage',
        updated: '2026-02-08',
      },
      {
        label: 'Organic matcha (UK)',
        href: '/best-organic-matcha-uk',
        tag: 'Drinks',
        desc: 'Starter‑friendly options with clear buying cues.',
        bestFor: 'Gentle caffeine swap',
        tradeOff: 'Taste varies a lot',
        updated: '2026-02-08',
      },
      {
        label: 'Matcha latte (UK): Ritual and Flow Matcha Flow',
        href: '/best-matcha-latte-uk-ritual-and-flow-matcha-flow',
        tag: 'Drinks',
        desc: 'A “better coffee alternative” option — what to check if you want energy without the crash.',
        bestFor: 'Daily energy routine',
        tradeOff: 'Taste preference',
        updated: '2026-02-13',
      },
      {
        label: 'Iced tea bundle (UK): Kaytea Ultimate Taster',
        href: '/best-iced-tea-uk-kaytea-ultimate-taster-bundle',
        tag: 'Drinks',
        desc: 'A low-friction “better drinks” swap: what to check (sweeteners, flavours, caffeine).',
        bestFor: 'Hydration + swaps',
        tradeOff: 'Stock + flavour preference',
        updated: '2026-02-13',
      },
      {
        label: 'High‑protein meal prep (UK)',
        href: '/high-protein-meal-prep-uk-the-good-prep-wild-berry-collagen-yoghurt',
        tag: 'Protein',
        desc: 'Meal prep as a bridge on busy weeks: reduce decision fatigue, keep it food-first.',
        bestFor: 'Busy weeks',
        tradeOff: 'Cost vs convenience',
        updated: '2026-02-11',
      },
      {
        label: 'Ethical meat delivery (UK)',
        href: '/ethical-meat-delivery-uk-real-food-hub-mangalitza-prime-rib',
        tag: 'Protein',
        desc: 'A guide to higher‑welfare meat delivery: what to look for and how to plan freezer space.',
        bestFor: 'Food-first protein',
        tradeOff: 'Storage + delivery windows',
        updated: '2026-02-11',
      },

    ],
  },
  {
    title: 'Supplements (beginner‑friendly)',
    desc: 'Conservative, UK‑friendly options with clear expectations.',
    items: [
      {
        label: 'Gut health supplements (beginners)',
        href: '/best-gut-health-supplements-beginners',
        tag: 'Gut',
        desc: 'Shortlist for simple, low‑risk gut support options.',
        bestFor: 'Digestion support',
        tradeOff: 'Start with food first',
        updated: '2026-02-08',
      },
      {
        label: 'Natural immune support',
        href: '/best-natural-immune-support-remedies',
        tag: 'Supplements',
        desc: 'Shortlist of simple immune‑support options.',
        bestFor: 'Seasonal support',
        tradeOff: 'Not a substitute for basics',
        updated: '2026-02-08',
      },
      {
        label: 'Creatine (UK)',
        href: '/best-creatine-supplement-uk-ancient-and-brave-true-creatine',
        tag: 'Supplements',
        desc: 'Creatine basics + a simple, hype-free buying guide.',
        bestFor: 'Strength + performance',
        tradeOff: 'Consistency required',
        updated: '2026-02-08',
      },
      {
        label: 'Collagen powder (UK): Ancient + Brave True Collagen',
        href: '/best-collagen-powder-uk-ancient-and-brave-true-collagen',
        tag: 'Supplements',
        desc: 'A practical collagen guide: what to check, how to trial it, and common mistakes.',
        bestFor: 'Skin + joints + connective tissue support',
        tradeOff: 'Consistency required',
        updated: '2026-02-13',
      },
      {
        label: 'AG1 travel packs (UK): Healf',
        href: '/best-ag1-travel-packs-uk-healf',
        tag: 'Supplements',
        desc: 'A greens powder guide focused on using it simply and avoiding “stacking”.',
        bestFor: 'Daily essentials (travel)',
        tradeOff: 'Higher ongoing cost',
        updated: '2026-02-13',
      },
      {
        label: 'Joint support supplement (UK): Revive Active Joint Complex',
        href: '/best-joint-support-supplement-uk-reviveactive-joint-complex',
        tag: 'Recovery',
        desc: 'A joint support guide for active people: what matters, what to avoid, how to trial.',
        bestFor: 'Daily joint support',
        tradeOff: 'Taste + consistency',
        updated: '2026-02-13',
      },
      {
        label: 'Daily essentials supplement (UK)',
        href: '/best-daily-essentials-supplement-uk-reviveactive-original',
        tag: 'Supplements',
        desc: 'A simple daily option — how to trial it without overcomplicating your routine.',
        bestFor: 'Daily support',
        tradeOff: 'Not a substitute for basics',
        updated: '2026-02-11',
      },
      {
        label: 'Omega‑3 (algae) supplement (UK)',
        href: '/best-algae-omega-3-supplement-uk-together',
        tag: 'Supplements',
        desc: 'Plant‑based omega‑3: what to check (DHA/EPA per serving) and how to compare options.',
        bestFor: 'Omega‑3 support',
        tradeOff: 'Serving size varies',
        updated: '2026-02-11',
      },
      {
        label: 'Vitamin D3 (UK)',
        href: '/best-vegan-vitamin-d3-supplement-uk-together',
        tag: 'Supplements',
        desc: 'UK‑friendly vitamin D basics: dose, stacking risks, and what to avoid.',
        bestFor: 'Winter support',
        tradeOff: 'Dose needs vary',
        updated: '2026-02-11',
      },
      {
        label: 'Electrolytes for training (UK)',
        href: '/best-electrolytes-hydration-supplement-uk-ancient-and-brave-true-hydration',
        tag: 'Supplements',
        desc: 'When electrolytes help (and when they don’t) — plus what to check per serving.',
        bestFor: 'Sweaty sessions',
        tradeOff: 'Sugar/sweeteners vary',
        updated: '2026-02-11',
      },

    ],
  },
  {
    title: 'Movement gear',
    desc: 'Simple gear that removes friction — not “must‑have” toys.',
    items: [
      {
        label: 'Resistance bands (home workouts)',
        href: '/best-resistance-bands-home-workouts',
        tag: 'Strength',
        desc: 'Shortlist for bands that cover most home training.',
        bestFor: 'Home strength',
        tradeOff: 'Progressive overload needs planning',
        updated: '2026-02-08',
      },
      {
        label: 'Yoga mats (grip + comfort)',
        href: '/best-yoga-mats-grip-comfort',
        tag: 'Mobility',
        desc: 'A short list focused on grip and comfort.',
        bestFor: 'Mobility + floor work',
        tradeOff: 'Thickness vs stability',
        updated: '2026-02-08',
      },
      {
        label: 'Walking shoes for daily steps (UK)',
        href: '/best-walking-shoes-daily-steps-uk',
        tag: 'Walking',
        desc: 'Comfort‑first shortlist for regular steps.',
        bestFor: 'Daily walking',
        tradeOff: 'Fit matters more than brand',
        updated: '2026-02-08',
      },
      {
        label: 'Foam rollers (recovery)',
        href: '/best-foam-rollers-recovery-tools',
        tag: 'Recovery',
        desc: 'Simple options for mobility + recovery.',
        bestFor: 'Tightness + mobility work',
        tradeOff: 'Technique matters',
        updated: '2026-02-08',
      },
      {
        label: 'Fitness trackers (beginners, UK)',
        href: '/best-fitness-trackers-beginners-uk',
        tag: 'Trackers',
        desc: 'Simple tracking without overthinking.',
        bestFor: 'Accountability',
        tradeOff: 'More data isn’t always better',
        updated: '2026-02-08',
      },
      {
        label: 'Smart scales (UK)',
        href: '/best-smart-scales-uk',
        tag: 'Scales',
        desc: 'Simple weigh‑in routines (with sensible expectations).',
        bestFor: 'Trend tracking',
        tradeOff: 'Body‑comp numbers are estimates',
        updated: '2026-02-08',
      },
      {
        label: 'Activewear basics (UK)',
        href: '/best-activewear-basics-uk',
        tag: 'Clothing',
        desc: 'Comfort‑first basics that make movement easier.',
        bestFor: 'Consistency',
        tradeOff: 'Materials vary by use',
        updated: '2026-02-08',
      },
      {
        label: 'Barefoot walking boots (UK)',
        href: '/best-barefoot-walking-boots-uk-vivobarefoot-tracker-winter-iii',
        tag: 'Walking',
        desc: 'A practical barefoot boots guide: transition safely and avoid overload.',
        bestFor: 'Outdoor walking',
        tradeOff: 'Needs slow transition',
        updated: '2026-02-11',
      },

      {
        label: 'Barefoot training shoes (UK): Vivobarefoot Primus Lite Knit',
        href: '/best-barefoot-training-shoes-uk-vivobarefoot-primus-lite-knit',
        tag: 'Footwear',
        desc: 'A barefoot training shoe guide: foot strength basics, transition cues, and what to avoid.',
        bestFor: 'Gym + strength training',
        tradeOff: 'Needs slow transition',
        updated: '2026-02-13',
      },

    ],
  },
]

export function flattenShortlists(sections = SHORTLIST_SECTIONS) {
  const out = []
  for (const s of sections || []) {
    for (const it of (s.items || [])) {
      out.push({ ...it, _sectionTitle: s.title })
    }
  }
  return out
}
