import Link from 'next/link'
import StructuredData from '@/components/StructuredData'
import { SITE_URL } from '@/lib/site'
import InterestSignup from '@/components/InterestSignup'

export const metadata = { title: 'Outdoors & Nature UK — Walking, Family Camping and Practical Gear', description: 'Practical UK guidance for walking, family camping, outdoor cooking, hydration, cycling, dogs outdoors and low-friction micro-adventures.' }

const ROUTES = [
  ['Walk more often', 'Build a repeatable walking habit, choose footwear by terrain and take weather and route conditions seriously.', '/blog/walking-for-health-how-much-is-enough', 'Start with walking'],
  ['Family camping', 'Plan shelter, sleep, warmth, food and hygiene before buying convenience extras.', '/outdoors/family-camping-checklist-uk', 'Use the camping framework'],
  ['Camping sleep systems', 'Match the mat, sleeping bag and night clothing to the coldest likely conditions and your type of camping.', '/outdoors/family-camping-sleep-system-uk', 'Build a warmer sleep system'],
  ['Outdoor hydration', 'Match carried water and treatment to the route; a filter does not remove every possible hazard.', '/water-filtration-shortlist-uk', 'Compare portable water routes'],
  ['Dogs outdoors', 'Balance distance, surface, weather, water and recovery around the individual dog.', '/blog/healthy-weight-exercise-dogs-uk', 'Plan activity with your dog'],
  ['Camping with dogs', 'Keep food, sleep, identification, temperature and campsite boundaries familiar and manageable.', '/outdoors/dog-camping-checklist-uk', 'Use the dog-camping checklist'],
  ['Fire and outdoor cooking', 'Choose a safe, durable cooking system for the place and people—not a social-media aesthetic.', '/outdoors/fire-cooking-safety-uk', 'Learn the safe foundations'],
  ['Portable power', 'Start with the devices, watt-hours and failure you need to cover before comparing batteries or panels.', '/healthy-home/home-energy', 'Understand portable power'],
]

export default function Page() { return <main className="mx-auto max-w-6xl px-4 py-16"><StructuredData data={{'@context':'https://schema.org','@type':'CollectionPage',name:'Outdoors & Nature UK',url:`${SITE_URL}/outdoors`,description:metadata.description}} /><header className="max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-emerald-900">Outdoors &amp; nature</p><h1 className="mt-2 text-4xl font-bold tracking-tight md:text-5xl">Spend more useful time outside</h1><p className="mt-4 max-w-3xl text-lg text-zinc-700">Accessible UK routes into walking, family camping, outdoor food and everyday nature. We organise around the activity and the decision—not piles of gear.</p><div className="mt-6 flex flex-wrap gap-2"><Link href="/movement" className="btn-primary">Build movement outdoors</Link><Link href="/dogs" className="btn-secondary">Take dogs outdoors well</Link><Link href="/deals" className="btn-secondary">Check current offers</Link></div></header><section className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{ROUTES.map(([title,text,href,label]) => <article key={title} className="rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-zinc-700">{text}</p><Link href={href} className="mt-5 inline-flex font-semibold underline underline-offset-4">{label} →</Link></article>)}</section><section className="mt-14 rounded-3xl border border-amber-900/10 bg-amber-50/60 p-6 md:p-8"><h2 className="text-2xl font-semibold">The no-regrets buying order</h2><ol className="mt-4 list-decimal space-y-2 pl-6 text-zinc-700"><li>Define the activity, people, season and likely conditions.</li><li>Borrow or use what you already own for the first low-risk trip.</li><li>Fix the biggest comfort or safety failure revealed by experience.</li><li>Buy durable, repairable equipment only when it earns repeat use.</li></ol></section><div className="mt-14"><InterestSignup placement="outdoors-hub" defaultInterest="outdoors" title="Make outside time easier to repeat" description="Seasonal UK walking, camping, outdoor-food and family nature guidance—plus only the offers that genuinely help." /></div></main> }
